# Preparing features and labels


In [1]:
#import paskages 
import tensorflow as tf

In [2]:
#create dataset 
dataset = tf.data.Dataset.range(10)

for v in dataset:
    print(v.numpy())

0
1
2
3
4
5
6
7
8
9


In [11]:
dataset= tf.data.Dataset.range(10)
dataset= dataset.window(5 ,shift=1)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy() , end=' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [12]:
dataset= tf.data.Dataset.range(10)
dataset= dataset.window(5 ,shift=1 , drop_remainder=True)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy() , end=' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [13]:
dataset= tf.data.Dataset.range(10)
dataset=dataset.window(5 , shift=1 , drop_remainder=True)
dataset= dataset.flat_map(lambda w:w.batch(5))
for w in dataset:
    print(w.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [16]:
dataset= tf.data.Dataset.range(10)
dataset=dataset.window(5 , shift=1 , drop_remainder=True)
dataset= dataset.flat_map(lambda w:w.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

for x,y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] 4
[1 2 3 4] 5
[2 3 4 5] 6
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9


In [18]:
dataset= tf.data.Dataset.range(10)
dataset=dataset.window(5 , shift=1 , drop_remainder=True)
dataset= dataset.flat_map(lambda w:w.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
dataset= dataset.shuffle(10)
for x,y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] 4
[5 6 7 8] 9
[4 5 6 7] 8
[2 3 4 5] 6
[3 4 5 6] 7
[1 2 3 4] 5


In [22]:
dataset= tf.data.Dataset.range(10)
dataset=dataset.window(5 , shift=1 , drop_remainder=True)
dataset= dataset.flat_map(lambda w:w.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
dataset= dataset.shuffle(10)
dataset=dataset.batch(2).prefetch(1)

for x,y in dataset:
    print('x = ' ,x.numpy())
    print('y = ',y.numpy())

x =  [[5 6 7 8]
 [4 5 6 7]]
y =  [9 8]
x =  [[1 2 3 4]
 [0 1 2 3]]
y =  [5 4]
x =  [[3 4 5 6]
 [2 3 4 5]]
y =  [7 6]
