# Generating Text with Neural Networks

In [1]:
#import paskaes 
import numpy as np
import tensorflow as tf 

from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

### Building the Word Vocabulary

In [2]:
#sample data 
data="In the town of Athy one Jeremy Lanigan \n Battered away til he hadnt a pound. \nHis father died and made him a man again \n Left him a farm and ten acres of ground. \nHe gave a grand party for friends and relations \nWho didnt forget him when come to the wall, \nAnd if youll but listen Ill make your eyes glisten \nOf the rows and the ructions of Lanigans Ball. \nMyself to be sure got free invitation, \nFor all the nice girls and boys I might ask, \nAnd just in a minute both friends and relations \nWere dancing round merry as bees round a cask. \nJudy ODaly, that nice little milliner, \nShe tipped me a wink for to give her a call, \nAnd I soon arrived with Peggy McGilligan \nJust in time for Lanigans Ball. \nThere were lashings of punch and wine for the ladies, \nPotatoes and cakes; there was bacon and tea, \nThere were the Nolans, Dolans, OGradys \nCourting the girls and dancing away. \nSongs they went round as plenty as water, \nThe harp that once sounded in Taras old hall,\nSweet Nelly Gray and The Rat Catchers Daughter,\nAll singing together at Lanigans Ball. \nThey were doing all kinds of nonsensical polkas \nAll round the room in a whirligig. \nJulia and I, we banished their nonsense \nAnd tipped them the twist of a reel and a jig. \nAch mavrone, how the girls got all mad at me \nDanced til youd think the ceiling would fall. \nFor I spent three weeks at Brooks Academy \nLearning new steps for Lanigans Ball. \nThree long weeks I spent up in Dublin, \nThree long weeks to learn nothing at all,\n Three long weeks I spent up in Dublin, \nLearning new steps for Lanigans Ball. \nShe stepped out and I stepped in again, \nI stepped out and she stepped in again, \nShe stepped out and I stepped in again, \nLearning new steps for Lanigans Ball. \nBoys were all merry and the girls they were hearty \nAnd danced all around in couples and groups, \nTil an accident happened, young Terrance McCarthy \nPut his right leg through miss Finnertys hoops. \nPoor creature fainted and cried Meelia murther, \nCalled for her brothers and gathered them all. \nCarmody swore that hed go no further \nTil he had satisfaction at Lanigans Ball. \nIn the midst of the row miss Kerrigan fainted, \nHer cheeks at the same time as red as a rose. \nSome of the lads declared she was painted, \nShe took a small drop too much, I suppose. \nHer sweetheart, Ned Morgan, so powerful and able, \nWhen he saw his fair colleen stretched out by the wall, \nTore the left leg from under the table \nAnd smashed all the Chaneys at Lanigans Ball. \nBoys, oh boys, twas then there were runctions. \nMyself got a lick from big Phelim McHugh. \nI soon replied to his introduction \nAnd kicked up a terrible hullabaloo. \nOld Casey, the piper, was near being strangled. \nThey squeezed up his pipes, bellows, chanters and all. \nThe girls, in their ribbons, they got all entangled \nAnd that put an end to Lanigans Ball."


In [3]:
#preprossing text 
corpus = data.lower().split("\n")

print(corpus)

['in the town of athy one jeremy lanigan ', ' battered away til he hadnt a pound. ', 'his father died and made him a man again ', ' left him a farm and ten acres of ground. ', 'he gave a grand party for friends and relations ', 'who didnt forget him when come to the wall, ', 'and if youll but listen ill make your eyes glisten ', 'of the rows and the ructions of lanigans ball. ', 'myself to be sure got free invitation, ', 'for all the nice girls and boys i might ask, ', 'and just in a minute both friends and relations ', 'were dancing round merry as bees round a cask. ', 'judy odaly, that nice little milliner, ', 'she tipped me a wink for to give her a call, ', 'and i soon arrived with peggy mcgilligan ', 'just in time for lanigans ball. ', 'there were lashings of punch and wine for the ladies, ', 'potatoes and cakes; there was bacon and tea, ', 'there were the nolans, dolans, ogradys ', 'courting the girls and dancing away. ', 'songs they went round as plenty as water, ', 'the harp tha

In [4]:
# Initialize the Tokenizer class
tokenizer = Tokenizer()

tokenizer.fit_on_texts(corpus)

In [7]:
## Define the total words.
# add 1 for the index `0` which is just the padding token.

total_words= len(tokenizer.word_index)+1
print(f'total words: {total_words}')

total words: 263


### Preprocessing the Dataset


In [8]:
# Initialize the sequences list
input_sequences = []

In [9]:
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        
        input_sequences.append(n_gram_sequence)

In [10]:
input_sequences

[[4, 2],
 [4, 2, 66],
 [4, 2, 66, 8],
 [4, 2, 66, 8, 67],
 [4, 2, 66, 8, 67, 68],
 [4, 2, 66, 8, 67, 68, 69],
 [4, 2, 66, 8, 67, 68, 69, 70],
 [71, 40],
 [71, 40, 20],
 [71, 40, 20, 21],
 [71, 40, 20, 21, 72],
 [71, 40, 20, 21, 72, 3],
 [71, 40, 20, 21, 72, 3, 73],
 [16, 74],
 [16, 74, 75],
 [16, 74, 75, 1],
 [16, 74, 75, 1, 76],
 [16, 74, 75, 1, 76, 33],
 [16, 74, 75, 1, 76, 33, 3],
 [16, 74, 75, 1, 76, 33, 3, 77],
 [16, 74, 75, 1, 76, 33, 3, 77, 22],
 [41, 33],
 [41, 33, 3],
 [41, 33, 3, 78],
 [41, 33, 3, 78, 1],
 [41, 33, 3, 78, 1, 79],
 [41, 33, 3, 78, 1, 79, 80],
 [41, 33, 3, 78, 1, 79, 80, 8],
 [41, 33, 3, 78, 1, 79, 80, 8, 81],
 [21, 82],
 [21, 82, 3],
 [21, 82, 3, 83],
 [21, 82, 3, 83, 84],
 [21, 82, 3, 83, 84, 7],
 [21, 82, 3, 83, 84, 7, 42],
 [21, 82, 3, 83, 84, 7, 42, 1],
 [21, 82, 3, 83, 84, 7, 42, 1, 43],
 [85, 86],
 [85, 86, 87],
 [85, 86, 87, 33],
 [85, 86, 87, 33, 44],
 [85, 86, 87, 33, 44, 88],
 [85, 86, 87, 33, 44, 88, 13],
 [85, 86, 87, 33, 44, 88, 13, 2],
 [85, 86, 

In [11]:
# Get the length of the longest line
max_sequence_len = max([len(x) for x in input_sequences])

input_sequences=np.array(pad_sequences(input_sequences  ,maxlen=max_sequence_len ,padding='pre'))

In [13]:
xs= input_sequences[:,:-1]
labels =input_sequences[:,-1]

In [17]:
labels

array([  2,  66,   8,  67,  68,  69,  70,  40,  20,  21,  72,   3,  73,
        74,  75,   1,  76,  33,   3,  77,  22,  33,   3,  78,   1,  79,
        80,   8,  81,  82,   3,  83,  84,   7,  42,   1,  43,  86,  87,
        33,  44,  88,  13,   2,  45,  89,  90,  91,  92,  93,  94,  95,
        96,  97,   2,  98,   1,   2,  99,   8,   9,  10,  13, 100, 101,
        23, 102, 103,   5,   2,  47,  17,   1,  24,   6, 104, 105,  48,
         4,   3, 106, 107,  42,   1,  43,  49,  25,  50,  18, 108,  25,
         3, 109, 111,  26,  47, 112, 113,  51,  52,   3, 114,   7,  13,
       115,  27,   3, 116,   6,  53, 117, 118, 119, 120,   4,  54,   7,
         9,  10,  11, 121,   8, 122,   1, 123,   7,   2, 124,   1, 126,
        28,  34, 127,   1, 128,  11,   2, 129, 130, 131,   2,  17,   1,
        49,  40,  19, 134,  25,  18, 135,  18, 136, 137,  26, 138, 139,
         4, 140,  55, 141, 143, 144,   1,   2, 145, 146, 147, 148, 149,
        12,   9,  10,  11, 150,   5, 151,   8, 152, 153,  25,   

In [15]:
# Convert the label into one-hot arrays
ys = tf.keras.utils.to_categorical(labels , num_classes=total_words)

In [16]:
ys

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
# Get sample sentence
sentence = corpus[0].split()
print(corpus[0])
print(f'sample sentence: {sentence}')

in the town of athy one jeremy lanigan 
sample sentence: ['in', 'the', 'town', 'of', 'athy', 'one', 'jeremy', 'lanigan']


In [20]:
# Initialize token list
token_list = []

In [21]:
for w in sentence:
    token_list.append(tokenizer.word_index[w])

In [22]:
print(token_list)


[4, 2, 66, 8, 67, 68, 69, 70]


In [28]:
# Pick element
elem_number = 6
print(f'token list: {xs[elem_number]}')
print(f'decoded to text: {tokenizer.sequences_to_texts([xs[elem_number]])}')

token list: [ 0  0  0  4  2 66  8 67 68 69]
decoded to text: ['in the town of athy one jeremy']


In [29]:
#print label 
#print(ys[elem_number])
print(np.argmax(ys[elem_number]))

70


In [36]:
elem_number=5
print(xs[5])
print(tokenizer.sequences_to_texts([xs[elem_number]]))

[ 0  0  0  0  4  2 66  8 67 68]
['in the town of athy one']
